inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - 'test/ui/ux/tables/table_test.rb'

Style/AsciiComments:
  Enabled: true
  Exclude:
    - 'test/**/**/**/**/*'

Metrics/ClassLength:
  Enabled: false

Style/FormatString:
  Exclude:
    - 'config/initializers/will_paginate.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  EnforcedStyle: unannotated
