inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - 'test/ui/ux/tables/table_test.rb'

Style/AsciiComments:
  Enabled: true
  Exclude:
    - 'test/**/**/**/**/*'

Metrics/ClassLength:
  Enabled: false

Style/FormatString:
  Exclude:
    - 'config/initializers/will_paginate.rb'

Style/StringLiterals:
  Enabled: true
  Exclude:
    - 'test/**/**/**/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  EnforcedStyle: unannotated

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
