language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=95196f8dbe3406321c6e7b406585532102784f0a3d4141a25f53937eedb844b6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
rvm:
  - 2.6.3
branches:
  only:
    - master
install:
  - "travis_retry bundle install"
addons:
  code_climate:
    repo_token: 95196f8dbe3406321c6e7b406585532102784f0a3d4141a25f53937eedb844b6 bundle exec rake
